Description: >
  Automated deployment for Cloud Simulation with docker on ec2

Resources:

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: lt-024c4f50b6fec6a93
        Version: '2'              
