services:
  backend:
    build:
      context: ..
      dockerfile: app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: usersdb
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.11
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: usersdb
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -h 127.0.0.1 -uroot -prootpass -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
